### ISSUE TITLE
Not working in firmware version AR_LBFIBRA_sp-00.03.05.211D

### ISSUE THREAD

**Issue by optiwiper** [segura2010/LiveboxFibraExtractor#1]
The data extraction system has stopped working with the new firmware version AR_LBFIBRA_en-00.03.05.211D.

Orange has updated all the routers automatically, blocking the data from being extracted again. Any information that can help is welcome.

Thank you.

**Comment by segura2010** [comment]
Yes, this way of extracting the information was fixed long time ago. This tool does not work in the recent versions and I do not have any plans to update it or search new ways of getting the SIP information.
